### ISSUE TITLE
Help or Q&A section in menu

### ISSUE THREAD

**Issue by maya-ux** [Lookyloo/lookyloo#109]
## Describe the change
*(A clear and concise description of what you want to happen)*

Currently there is no any help section nor Q&A section in the main menu. 

## How will this impact users?

Would give the users more information on what they can do with Lookyloo. 

## To which release does this apply?

- [] Current release
- [] Future release 

## Additional context
*(Add any other context or screenshots about the feature request here)*

1. 
1. 
1.

**Comment by Rafiot** [comment]
TODO: Add a link to the documentation website (https://www.lookyloo.eu/docs/main/usage.html) when it will be more complete.

Or do you have an other idea?

**Comment by maya-ux** [comment]
I would say that a link to the documentation website would do the work.
We can always ask users about its content at some point in order to know whether something is missing or not.

**Comment by Rafiot** [comment]
Sounds good :)

**Comment by Rafiot** [comment]
done.
