### ISSUE TITLE
Back/Forth Button missing

### ISSUE THREAD

**Issue by maya-ux** [Lookyloo/lookyloo#110]
## What is changing? 
*(Please include as many details as possible)*

Currently there is no back/forth button anywhere on the platform. The only way to go back  from the tree page to the search page, is by clicking on the Lookyloo logo or right-click with the mouse, but this is not very intuitive.

## How will this impact users?
Would give them more options and flexibility to move around and to figure it out more easily. 

## To which release does this apply?

- [] Current release
- [] Future release 

## Context
Link to associated PRs or issues from other repos here.

1.
1.
1.

**Comment by Rafiot** [comment]
TODO: add a "Home" button in the menu
