### ISSUE TITLE
Error messages are not visible

### ISSUE THREAD

**Issue by maya-ux** [Lookyloo/lookyloo#112]
## What is changing? 
*(Please include as many details as possible)*

When you open an investigation pop-up window to research details further and you get an error, the message is displayed behind the investigation pop-up window itself, making it invisible to user. 

Currently, only when you close the investigation pop-up window you see the error message, and it should be viceversa. 

## How will this impact users?

Will allow users to take action and know what is going on, as currently you see the investigation window waiting for results but there is no indication what is wrong and you wonder, while the message is displayed in the background but you don't see it. 

## To which release does this apply?

- [] Current release
- [] Future release 

## Context
Link to associated PRs or issues from other repos here.

1.
1.
1.

## Additional information
<img width="1110" alt="Exploring captures:node results section" src="https://user-images.githubusercontent.com/73597975/97456865-84fdfc00-1939-11eb-8376-4318631bdb12.png">
<img width="1112" alt="Error message in the background" src="https://user-images.githubusercontent.com/73597975/97456916-8e876400-1939-11eb-8443-2a2125cc49b2.png">

**Comment by Rafiot** [comment]
Note: the popup causing an issue is the one triggered by a click **in** an investigation popup.

TODO:
* [ ] Figure out in which condition we can open the investigation popup, and still get the error
* [ ] bubble up the alert message to the hostnode investigation popup
