### ISSUE TITLE
Flag/unflag feature unclear

### ISSUE THREAD

**Issue by maya-ux** [Lookyloo/lookyloo#114]
## What is changing? 
*(Please include as many details as possible)*

Flag/unflag all nodes /from main menu/ is unclear. 
Probably is a question of providing information to users in the help or Q&A section. 

## To which release does this apply?

- [] Current release
- [] Future release 

## Context
Link to associated PRs or issues from other repos here.

1.
1.
1.

**Comment by Rafiot** [comment]
TODO:
* [ ] rename flag -> bookmark
* [ ] add the bookmarked nodes in the user session, so it stays on page reload
