### ISSUE TITLE
Action buttons/ inconsistency of colours

### ISSUE THREAD

**Issue by maya-ux** [Lookyloo/lookyloo#115]
## What is changing? 
*(Please include as many details as possible)*
Actions buttons in investigation pop-up windows and actions buttons within options of the main menu are of different colours.

## How will this impact users?
It is always good to keep consistency. 

## To which release does this apply?

- [] Current release
- [] Future release 

## Context
Link to associated PRs or issues from other repos here.

1.
1.
1.

**Comment by Rafiot** [comment]
TODO: Turn all the buttons to the same color -> https://getbootstrap.com/docs/4.0/components/buttons/
