### ISSUE TITLE
Expanding bit.ly/URLs+ result in a blank screenshot.

### ISSUE THREAD

**Issue by SteveClement** [Lookyloo/lookyloo#166]
## Expected behavior

When expanding a bit.ly link by appending a + at the end of the URL it should grab a screenshot of the output.

## Actual behavior

Blank page

Sample: https://lookyloo.circl.lu/tree/2e5c1dc4-5bca-456f-8f6e-92d8b545264f

## Steps to reproduce the problem

1. Look for: https://bitly.com/CA-ITALIA+
2. ???
3. Profit

## Additional information

Maybe cloudfront related...

**Comment by Rafiot** [comment]
Oh, interesting, I didn't know that bitly trick.

There are a few situations where the rendered page is white, and it happens is pretty random situations. In this case, I guess it is because the call to `window.InfoPlus.start` somehow fails?
