### ISSUE TITLE
Index URLs

### ISSUE THREAD

**Issue by Rafiot** [Lookyloo/lookyloo#179]
Current status

The only way to search for URls is to use the index and search box, it will only work on the content of the table.

## New features

It would be nice to have an index of the URLs (at least the redirects) in a redis DB so we can get the related captures, and opening that to the API.

Also, for the API, having the option to return the an existing capture for that URL if it was already captured in the last X hours.

* [x] Index URLs in redis
* [x] Lookup API in pylookyloo
* [x] Get UUID of capture for a URL, if it was captured in the last X hours

**Comment by FafnerKeyZee** [comment]
Hey,

It could be nice to have a list of all UUID for a given URL, in case a URL was analyzed multiple times (with the analysis date in the answer)

**Comment by Rafiot** [comment]
So it is already (partially) implemented (https://github.com/Lookyloo/PyLookyloo/blob/main/pylookyloo/api.py#L145), but there are a few limitations:
* the indexing is only done if the capture is cached (so you won't have a hit unless the capture has been rendered at least once)
* on common URLs, the query is super slow (lots of captures to return)
* the list of captures is in a random order (instead of being sorted most recent -> oldest)

Fixes:
* add background job to auto-cache captures
* Add limit of captures to return
* Sort captures by date
