### ISSUE TITLE
Do not zip the downloaded content 

### ISSUE THREAD

**Issue by Rafiot** [Lookyloo/lookyloo#189]
## What is changing? 

The contents are zipped on download, that step should be skipped.

## How will this impact users?

Directly get the file they expect to download instead of unzipping before they can do anything with it.

## Context

It's just an extra step that doesn't give anything (the users will just open the file from the zip, whatever that is).

## Additional information

All the images should be returned as images, and everything else as text (mimetype text, and .txt extension appended), in order to avoid mistakenly opening HTML files into browsers, or running exe files for example.

**Comment by francastagna** [comment]
Hey! I would like to work on this issue 💻
