### ISSUE TITLE
Integrating WHOIS data

### ISSUE THREAD

**Issue by quinnnorton** [Lookyloo/lookyloo#194]
## What is changing? 
Probably as a tool inside the nodes. 

## Context

1.
1.

**Comment by Rafiot** [comment]
Feature implemented by https://github.com/Lookyloo/lookyloo/commit/3389dcafd6cd676aae1c5809323277b425759dab

It requires access to an instance of [uWhoisd](https://github.com/Lookyloo/uwhoisd).
