### ISSUE TITLE
Punycode urls don't work

### ISSUE THREAD

**Issue by iglocska** [Lookyloo/lookyloo#198]
xn--gmail-rq8m.com

![image](https://user-images.githubusercontent.com/3668672/114741214-d44eb200-9d4a-11eb-982e-49bd033f5c5d.png)

As reported by a manager that can't use github but quite fancies a horse related scene in the Godfather.

**Comment by Rafiot** [comment]
A punycode domain that resolve seems to be working just fine: xn--mnich-kva.com -> https://lookyloo.circl.lu/tree/dcf80f0c-2a1d-4c63-9c2a-3ba2a8b6f7c7
