### ISSUE TITLE
Referer value is not shown in capture details view.

### ISSUE THREAD

**Issue by Wachizungu** [Lookyloo/lookyloo#224]
## Expected behavior
The referer value is shown in the capture details view if it was set for the capture

## Actual behavior
The referer value is missing

## Steps to reproduce the problem

1.Run a capture with referer header set
2.Check capture details view

## Additional information
Example run: https://lookyloo.circl.lu/tree/5f6251fc-cadb-4d61-aa2f-72f21b155811

**Comment by Rafiot** [comment]
Good point, I'll add that. We may also want to add a reference to the cookies somewhere (if present).

**Comment by adulau** [comment]
Having @Wachizungu reporting bugs and feature, it's a great news for the Lookyloo project ;-) 😄

**Comment by Wachizungu** [comment]
Fixed in https://github.com/Lookyloo/lookyloo/commit/20fb7a70f945cee905751f4b044dcec03e59dbf8

Thanks a lot!
