### ISSUE TITLE
body_hashes view shows a huge amount of entries below 'The same file was seen in these captures:' where the file probably wasn't seen

### ISSUE THREAD

**Issue by Wachizungu** [Lookyloo/lookyloo#227]
## Expected behavior
body_hashes view only lists captures that detected the same file and the links lead to those captures (or the entries shouldn't be a link I guess)

## Actual behavior
body_hashes just dumps a huge list of links, that don't even actually lead to captures

## Steps to reproduce the problem

As an example, just go to:

https://lookyloo.circl.lu/body_hashes/10a596b3565c036658f656cb2123f3f1a191dbe2fb25562a040613ab90178019128d14ae4041aa5b1f11d73017d7a29d5cf6828ce09a284f0c0a9534c1c1e51c?from_popup=True#/

I got to one of those by starting a capture, then clicking on the tree element showing js and css files and finally clicking on 'Show more information about this response body'.

If you want to follow the exact trail, https://lookyloo.circl.lu/tree/de2281f4-e36e-4998-a353-9e3584999ff1, click on cloaking.jeroenpinoy.website (8), click on 'Show more information about this response body.' below ... / static/css/sticky-footer-navbar.css.

## Additional information
Note that the info below sticky-footer-navbar.css says 'This file can be found 1 times across all the captures on this lookyloo instance, in 1 unique domains.'. 

I'm a bit at a loss what is going on in this particular case, so sorry if the description and assumptions above are a bit off.

**Comment by Rafiot** [comment]
That's a very weird bug in fact, and it doesn't seem to be happening often either. I'm investigating.

**Comment by Rafiot** [comment]
That last commit should solve it, thanks for the report!

**Comment by Wachizungu** [comment]
:O cool, thanks!
