### ISSUE TITLE
Feature request: predictable URL to start a capture in a browser

### ISSUE THREAD

**Issue by pgl** [Lookyloo/lookyloo#248]
## What is changing? 

Adding a predictable URL that can be visited in a browser, that starts a new capture.

## How will this impact users?

Very similar to #246, but this would allow users to go to a URL in a browser that would start a new capture of a site.

eg:

 * https://lookyloo.circl.lu/capture?url=example.com

This would show the wait page as currently happens when filling in the form and submitting via POST.

The reason for this is so that web apps, and custom search engines, can easily link from inside their app to Lookyloo and not have to integrate with an API endpoint.

## Context

1. #246 
2. Twitter thread: https://twitter.com/pgl/status/1427533143754616852

**Comment by Rafiot** [comment]
Ahh, ok, I get your point. Initially I thought it was for integrating in a system that was only capable of GET requests.

I'll add that tomorrow.

**Comment by Rafiot** [comment]
That should be sorted now! I'll update the public instance in a few min.

**Comment by pgl** [comment]
@Rafiot OK, that's amazing, and you're amazing, and now I'm going to add it everywhere.

**Comment by Rafiot** [comment]
wohoo :) 
Let me know how it goes! And depending on how private these things you're adding it to are, you may want to setup a dedicated lookyloo instance: this one is part demo, part dev, and only kinda prod, so sometimes, some captures may go away ;)
