### ISSUE TITLE
CSV export

### ISSUE THREAD

**Issue by Th4nat0s** [Lookyloo/lookyloo#26]
Will be nice ( yes again )....

To have the capacity to export the data, json is an option but most of the time CSV is the usable by most people.

HIT, Called by, [type... javascript, cookie, etc..]

vala :)

**Comment by Rafiot** [comment]
The question here is what do you want to get in the Json/CSV? because there is a shitload (that's a technical term) or information and you definitely don't want all of it, I promise :)

**Comment by Th4nat0s** [comment]
For what we do, the CSV as describe will be enought. Har package Download why not another day :)

**Comment by Rafiot** [comment]
For the called by, do you want just the direct parent? What to do if there are multiple layers? Should it be the full URL, or the domain?

As each node can have multiple URLs, how should it be represented?

**Comment by Rafiot** [comment]
There are a few export options implemented now, closing this one.
