### ISSUE TITLE
Scraping improvements

### ISSUE THREAD

**Issue by Rafiot** [Lookyloo/lookyloo#45]
* [x] Proxy support 
* [x] Pass a pre-generated cookie
* [x] Initial referrer
* [ ] Locale of the browser
* [x] Login creds <= how to pass them properly in the webpage will be challenging (solved by passing a valid cookie)

**Comment by quinnnorton** [comment]
also ability to pass login creds

**Comment by Rafiot** [comment]
(added in the list)

The first step will be to pass a cookie. Passing the credentials in a webpage without user interaction will be challenging.

**Comment by quinnnorton** [comment]
we should think about how we can push this back on the lookyloo user wrt internal or often used sites... can they do the config so it's not a general case?

**Comment by Rafiot** [comment]
This commit (https://github.com/CIRCL/lookyloo/commit/f1d83d29cf51dd0f9daa74553257e6f4eff1e662) allows to load cookies exported via https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/

The way to go is to dump a file `cookies.json` in JSON format (the default of the plugin) in the root directory of lookyloo. The File will be automatically loaded, every cookies converted in the HAR cookies format (as required by splash), and sent along with the initial query when scraping a website.

**Comment by Rafiot** [comment]
For Proxy support, see example 5 there: https://splash.readthedocs.io/en/stable/scripting-ref.html#splash-on-request

**Comment by Rafiot** [comment]
Done.
