### ISSUE TITLE
Reorganize scraping page

### ISSUE THREAD

**Issue by Rafiot** [Lookyloo/lookyloo#47]
It is currently clumsy and difficult to use, need a mockup.

Missing functionalities listed here: https://github.com/CIRCL/lookyloo/issues/45

**Comment by quinnnorton** [comment]
mockup: 
<img width="948" alt="Screenshot 2019-05-28 at 15 31 44" src="https://user-images.githubusercontent.com/4722614/58485300-0b6e4700-8164-11e9-9a4b-374365bdb4bf.png">

**Comment by Rafiot** [comment]
(reopening and assigning it to myself so I implement that)

**Comment by Rafiot** [comment]
The lookup against 3rd party services should be done from the tree page instead: which 3rd party service to query when is hard to decide from the scraping page. 

And it will require making too many requests against services where there is a daily limit.
