### ISSUE TITLE
[Feature]: Allow to upload an HAR file

### ISSUE THREAD

**Issue by FafnerKeyZee** [Lookyloo/lookyloo#549]
### Is your feature request related to a problem? Please describe.

In some case, we have to deal with HAR file, extracted from an other source, and we want to create a tree to have a better view :)

### Describe the solution you'd like

Add a new tab on the submit page in order to upload our HAR file.

**Comment by Rafiot** [comment]
Done: https://github.com/Lookyloo/lookyloo/commit/3c1cbd6ece4e81fc025592cfd8d5ce12f5ff3590 https://github.com/Lookyloo/lookyloo/commit/c006d53d5d7bf8a79b2f1cdc10836e37ecf3c58f
