### ISSUE TITLE
DarkMode for the UI

### ISSUE THREAD

**Issue by InfoSecN00b42** [Lookyloo/lookyloo#61]
It hurts my eyes in the dark.

**Comment by Rafiot** [comment]
hehehe, sure. It's not super high on my priority list, but if you come with a reasonable PR, I'll gladly merge it.

**Comment by InfoSecN00b42** [comment]
Well it seems to be not as trivial as expected, I will make a PR draft thing.
Quite some images have white backgrounds.
And the entire svg thing seems to be not too happy with implementing another theme or the like,.

**Comment by Rafiot** [comment]
Closing this one for now, will be covered by PR.
