### ISSUE TITLE
[Feature]: Status Code for a capture via the API

### ISSUE THREAD

**Issue by FafnerKeyZee** [Lookyloo/lookyloo#669]
### Is your feature request related to a problem? Please describe.

Hard to obtain the final status code of a capture

### Describe the solution you'd like

Add the information in the
/json/{capture_uuid}/info

```
{
  "url": "https://myurlf",
  "title": "my title",
  "capture_time": "2023-04-18T16:29:57.353000+00:00",
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.5615.29 Safari/537.36",
  "referer": ""
  "status_code":"XXX"
}
```

**Comment by Rafiot** [comment]
Fixed: https://github.com/Lookyloo/lookyloo/commit/c62032fee2555b12b7f66f625d217d216be489ce
