### ISSUE TITLE
Use Tor to access .onion 

### ISSUE THREAD

**Issue by chervaliery** [Lookyloo/lookyloo#71]
Hi,

It would be nice to have the possibility to enable tor for some request to have access to .onion domains.

**Comment by Rafiot** [comment]
Hi,

Good point, it shouldn't be that difficult, I'll look at that

**Comment by Rafiot** [comment]
Note: I got it to work when using aquarium (https://github.com/Lookyloo/aquarium), but only on a fresh install.

**Comment by FafnerKeyZee** [comment]
It's should be solve with the next update \o/

**Comment by Rafiot** [comment]
Fixed by https://github.com/Lookyloo/lookyloo/pull/201 ! Thank you @FafnerKeyZee

**Comment by chervaliery** [comment]
Thanks a lot!
