### ISSUE TITLE
adding IP and Port in config

### ISSUE THREAD

**Issue by FafnerKeyZee** [Lookyloo/lookyloo#84]
## What is changing? 
* Add the possibility to set a specific interface (IP) and port for running the webserver. It could be better if we use a Ngix proxy ;)

**Comment by Rafiot** [comment]
Fixed by: https://github.com/Lookyloo/lookyloo/commit/7a34095d9c18f2efde8b16c9f1a09d6038ca2786

It worked for me out of the box, but you probably want to give it a try before pushing that in prod :]
