### ISSUE TITLE
Add a mobile OS/UserAgent

### ISSUE THREAD

**Issue by SteveClement** [Lookyloo/lookyloo#85]
## What is changing?

Add a mobile OS/UserAgent pair for sites that want to deliver a mobile site.

Example: https://lookyloo.circl.lu/tree/42e20a07-a1d4-4df5-884d-58f2d877cba4

**Comment by Rafiot** [comment]
Need to work on the UAs, related: https://github.com/Lookyloo/lookyloo/issues/77
