### ISSUE TITLE
Make the dockerized setup working

### ISSUE THREAD

**Issue by Rafiot** [Lookyloo/lookyloo#94]
At this point, the dockerized setup is non-functional. It would be nice to update/fix the half backed stuff we have right now.

For reference, the install guide for the lookyloo is there: 
https://www.lookyloo.eu/docs/main/install-lookyloo.html

Please get in touch with me if you start working on it.

**Comment by raulsoledispa** [comment]
Hi, I would like to can help you. Can you assign me it?

**Comment by Rafiot** [comment]
Hi, sure

**Comment by Rafiot** [comment]
@raulsoledispa just checking in: did you start working on that?

**Comment by raulsoledispa** [comment]
@Rafiot Yes, I'm working in the project

**Comment by Rafiot** [comment]
Thank you! Let me know if you have any question.

**Comment by Rafiot** [comment]
Hey @raulsoledispa, I hope you're good. Do you think you will manage to make a PR?
