### ISSUE TITLE
[Feature]: Improvement to the MISP export to add the first_seen on objects and attributes

### ISSUE THREAD

**Issue by adulau** [Lookyloo/lookyloo#985]
### Is your feature request related to a problem? Please describe.

Adding the first_seen on objects and attributes on the exported element when the capture was done.

### Describe the solution you'd like

Adding the first_seen on all attributes/objects referenced to the original capture time (and not the MISP submission time)

**Comment by Rafiot** [comment]
I'm finding quite a few bugs int he MISP export, that should be in prod relatively soon.

Quick question while I'm at it: does it makes sense to add the same first seen to *all* the attributes and objects? Or should I add it only once to the starting point of the capture?
